### ISSUE TITLE
Paste from Windows clipboard

### ISSUE THREAD

**Issue by humphreylee** [uncomfyhalomacro/erudite-vim#10]
Can you add configuration to paste from Windows' clipboard eg below (just an idea)? 
`vim.opt.clipboard = vim.opt.clipboard + 'unnamedplus';
vim.opt.autowrite = true`
Thanks.

**Comment by uncomfyhalomacro** [comment]
https://github.com/uncomfyhalomacro/erudite-vim/commit/2cff9bf6f4fcabb90be430ec1bfaf4faaea08244
